name: bhadrapurnagarpalika
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:       # CRITICAL: Required for every Flutter project - DO NOT REMOVE
   sdk: flutter # CRITICAL: Required for every Flutter project - DO NOT REMOVE
  http: ^1.2.1
  image_picker: ^1.0.4
  file_picker: ^8.0.0
  firebase_core: ^2.13.0 # Ensure you're using the latest version
  firebase_auth: ^4.0.0   # Firebase Auth for authentication7
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^6.2.1
  firebase_auth_web: ^5.8.13
  google_api_availability: ^5.0.1
  # CRITICAL: Core UI and responsive design - DO NOT REMOVE OR MODIFY
  sizer: ^2.0.15              # Required for responsive design system
  flutter_svg: ^2.0.9        # Required for SVG icon support
  google_fonts: ^6.1.0       # Required for typography (replaces local fonts)
  shared_preferences: ^2.2.2 # Required for local data storage
  web: ^1.1.1

  # Feature dependencies - safe to modify
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0

  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:    # CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter   # CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  flutter_lints: ^5.0.0 # CRITICAL: Required for code quality - DO NOT REMOVE

dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.15  # Try an older or newer version

flutter:
  uses-material-design: true # CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - assets/images/logo.png
    - assets/images/
  # CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)

  # CRITICAL FONTS RULE:
  # - THIS PROJECT USES GOOGLE FONTS INSTEAD OF LOCAL FONTS
  # - DO NOT ADD ANY LOCAL FONTS SECTION OR FONT FILES