class LanguageManager {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'ne': {
      // Basic UI
      'language': 'भाषा',
      'change_language': 'भाषा परिवर्तन गर्नुहोस्',
      'logout': 'लगआउट',
      'logout_confirm': 'के तपाईं लगआउट गर्न चाहनुहुन्छ?',
      'cancel': 'रद्द गर्नुहोस्',
      'profile': 'प्रोफाइल',
      'personal_info': 'व्यक्तिगत जानकारी',
      'work_info': 'कार्यालय जानकारी',
      'account_settings': 'खाता कार्यहरू',
      'change_password': 'पासवर्ड परिवर्तन गर्नुहोस्',
      'notifications': 'सूचना सेटिङहरू',
      'help_support': 'मद्दत र सहयोग',
      'language_changed': 'भाषा परिवर्तन गरियो',
      'language_change_failed': 'भाषा परिवर्तन गर्न असफल भयो',
      'select_language': 'भाषा चयन गर्नुहोस्',
      'welcome_message': 'स्वागत छ, {name}!',
      'google_account_connected': 'तपाईंको Google खाता कनेक्ट भयो।',
      'complaint_important': 'तपाईंको गुनासो महत्वपूर्ण छ।',
      'home': 'गृह',
      'my_complaints': 'मेरा गुनासोहरू',
      'pending_work': 'काम भैरहेको',
      'completed_complaints': 'सम्पूर्ण गुनासो',

      // Dashboard
      'officer_dashboard': 'अधिकृत ड्यासबोर्ड',
      'complaint_categories': 'गुनासो श्रेणीहरू',
      'incoming_complaints': 'आएको गुनासो',
      'all_complaints': 'सम्पूर्ण गुनासो',
      'resolved_complaints': 'समाधान गरेको गुनासो',
      'recent_complaints': 'हालका गुनासोहरू',
      'view_all': 'सबै हेर्नुहोस्',
      'main_functions': 'मुख्य कार्यहरू',
      'complaints_management': 'गुनासो व्यवस्थापन',
      'notice_board': 'सूचना बोर्ड',
      'submit_complaint': 'गुनासो पेश गर्नुहोस्',
      'data_updated': 'डाटा अपडेट भयो',
      'loading_data': 'डाटा लोड गर्दै...',

      // Complaints
      'complaints': 'गुनासोहरू',
      'complaint_management': 'गुनासो व्यवस्थापन',
      'search_complaints': 'गुनासो खोज्नुहोस्...',
      'filter': 'फिल्टर',
      'all': 'सबै',
      'pending': 'बाँकी',
      'in_progress': 'प्रगतिमा',
      'resolved': 'सम्पन्न',
      'complaint_details': 'गुनासो #',
      'view_details': 'विस्तृत हेर्नुहोस्',
      'update_status': 'स्थिति अपडेट गर्नुहोस्',
      'contact_citizen': 'नागरिकलाई सम्पर्क गर्नुहोस्',
      'no_complaints': 'कुनै गुनासो छैन',
      'no_search_results': 'खोजेको गुनासो फेला परेन',

      // Notice Board
      'notice_board_management': 'सूचना बोर्ड व्यवस्थापन',
      'all_notices': 'सबै',
      'published': 'प्रकाशित',
      'draft': 'ड्राफ्ट',
      'search_notices': 'सूचना खोज्नुहोस्...',
      'add_notice': 'नयाँ सूचना',
      'notice_published': 'सूचना प्रकाशित गरियो',
      'notice_saved_draft': 'सूचना ड्राफ्टमा सेभ गरियो',
      'notice_updated': 'सूचना अपडेट गरियो',
      'notice_deleted': 'सूचना मेटाइयो',
      'delete_notice_confirm': 'के तपाईं यो सूचना मेटाउन निश्चित हुनुहुन्छ?',
      'delete': 'मेटाउनुहोस्',
      'no_notices': 'कुनै सूचना छैन',

      // Officer Complaint Form
      'officer_complaint_form': 'अधिकृत गुनासो फारम',
      'complaint_title': 'गुनासोको शीर्षक',
      'complaint_description': 'गुनासोको विवरण',
      'location': 'स्थान',
      'contact_number': 'सम्पर्क नम्बर',
      'priority': 'प्राथमिकता',
      'category': 'श्रेणी',
      'submit_to_office': 'पेश गर्ने कार्यालय',
      'urgent': 'अत्यधिक महत्वपूर्ण (तत्काल कारबाही आवश्यक)',
      'attach_files': 'कागजात संलग्न गर्नुहोस्',
      'gallery': 'ग्यालरी',
      'camera': 'क्यामरा',
      'file': 'फाइल',
      'files_selected': 'फाइलहरू सफलतापूर्वक थपियो',
      'photo_added': 'फोटो सफलतापूर्वक थपियो',
      'file_load_failed': 'फाइल लोड गर्न असफल',
      'photo_load_failed': 'फोटो लोड गर्न असफल',
      'submit': 'गुनासो पेश गर्नुहोस्',
      'submitting': 'गुनासो पेश गर्दै...',
      'complaint_submitted': 'गुनासो सफलतापूर्वक पेश गरियो',
      'submission_failed': 'गुनासो पेश गर्न असफल',
      'fill_required_fields': 'कृपया सबै आवश्यक फिल्डहरू भर्नुहोस्',
      'attach_files_confirm': 'कागजात संलग्न गर्नुहुन्छ?',
      'add_files': 'फाइल थप्नुहोस्',
      'continue': 'जारी राख्नुहोस्',

      // Status and Priority
      'high': 'उच्च',
      'medium': 'मध्यम',
      'low': 'न्यून',
      'completed': 'सम्पन्न',
      'under_review': 'अन्तिम निर्णयमा',
      'citizen_name': 'नागरिकको नाम',
      'submission_date': 'दर्ता मिति',
      'ward': 'वडा',
      'status': 'स्थिति',

      // Offices
      'district_office': 'जिल्ला कार्यालय',
      'province_office': 'प्रदेश कार्यालय',
      'central_office': 'केन्द्रीय कार्यालय',
      'ministry': 'मन्त्रालय',

      // Categories
      'general_administration': 'सामान्य प्रशासन',
      'infrastructure': 'पूर्वाधार विकास',
      'sanitation': 'सफाई तथा सरसफाई',
      'health': 'स्वास्थ्य सेवा',
      'education': 'शिक्षा',
      'security': 'सुरक्षा',
      'financial': 'वित्तीय',
      'other': 'अन्य',
    },
    'en': {
      // Basic UI
      'language': 'Language',
      'change_language': 'Change Language',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'profile': 'Profile',
      'personal_info': 'Personal Information',
      'work_info': 'Work Information',
      'account_settings': 'Account Settings',
      'change_password': 'Change Password',
      'notifications': 'Notification Settings',
      'help_support': 'Help & Support',
      'language_changed': 'Language changed',
      'language_change_failed': 'Failed to change language',
      'select_language': 'Select Language',
      'welcome_message': 'Welcome, {name}!',
      'google_account_connected': 'Your Google account is connected.',
      'complaint_important': 'Your complaint is important.',
      'home': 'Home',
      'my_complaints': 'My Complaints',
      'pending_work': 'Pending Work',
      'completed_complaints': 'Completed Complaints',

      // Dashboard
      'officer_dashboard': 'Officer Dashboard',
      'complaint_categories': 'Complaint Categories',
      'incoming_complaints': 'Incoming Complaints',
      'all_complaints': 'All Complaints',
      'resolved_complaints': 'Resolved Complaints',
      'recent_complaints': 'Recent Complaints',
      'view_all': 'View All',
      'main_functions': 'Main Functions',
      'complaints_management': 'Complaints Management',
      'notice_board': 'Notice Board',
      'submit_complaint': 'Submit Complaint',
      'data_updated': 'Data Updated',
      'loading_data': 'Loading Data...',

      // Complaints
      'complaints': 'Complaints',
      'complaint_management': 'Complaint Management',
      'search_complaints': 'Search complaints...',
      'filter': 'Filter',
      'all': 'All',
      'pending': 'Pending',
      'in_progress': 'In Progress',
      'resolved': 'Resolved',
      'complaint_details': 'Complaint #',
      'view_details': 'View Details',
      'update_status': 'Update Status',
      'contact_citizen': 'Contact Citizen',
      'no_complaints': 'No complaints found',
      'no_search_results': 'No search results found',

      // Notice Board
      'notice_board_management': 'Notice Board Management',
      'all_notices': 'All',
      'published': 'Published',
      'draft': 'Draft',
      'search_notices': 'Search notices...',
      'add_notice': 'Add Notice',
      'notice_published': 'Notice published',
      'notice_saved_draft': 'Notice saved as draft',
      'notice_updated': 'Notice updated',
      'notice_deleted': 'Notice deleted',
      'delete_notice_confirm': 'Are you sure you want to delete this notice?',
      'delete': 'Delete',
      'no_notices': 'No notices found',

      // Officer Complaint Form
      'officer_complaint_form': 'Officer Complaint Form',
      'complaint_title': 'Complaint Title',
      'complaint_description': 'Complaint Description',
      'location': 'Location',
      'contact_number': 'Contact Number',
      'priority': 'Priority',
      'category': 'Category',
      'submit_to_office': 'Submit to Office',
      'urgent': 'Urgent (Immediate action required)',
      'attach_files': 'Attach Files',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'file': 'File',
      'files_selected': 'Files added successfully',
      'photo_added': 'Photo added successfully',
      'file_load_failed': 'Failed to load file',
      'photo_load_failed': 'Failed to load photo',
      'submit': 'Submit Complaint',
      'submitting': 'Submitting complaint...',
      'complaint_submitted': 'Complaint submitted successfully',
      'submission_failed': 'Failed to submit complaint',
      'fill_required_fields': 'Please fill all required fields',
      'attach_files_confirm': 'Do you want to attach files?',
      'add_files': 'Add Files',
      'continue': 'Continue',

      // Status and Priority
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'completed': 'Completed',
      'under_review': 'Under Review',
      'citizen_name': 'Citizen Name',
      'submission_date': 'Submission Date',
      'ward': 'Ward',
      'status': 'Status',

      // Offices
      'district_office': 'District Office',
      'province_office': 'Province Office',
      'central_office': 'Central Office',
      'ministry': 'Ministry',

      // Categories
      'general_administration': 'General Administration',
      'infrastructure': 'Infrastructure',
      'sanitation': 'Sanitation',
      'health': 'Health',
      'education': 'Education',
      'security': 'Security',
      'financial': 'Financial',
      'other': 'Other',
    },
    'hi': {
      // Basic UI
      'language': 'भाषा',
      'change_language': 'भाषा बदलें',
      'logout': 'लॉगआउट',
      'logout_confirm': 'क्या आप लॉगआउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'profile': 'प्रोफ़ाइल',
      'personal_info': 'व्यक्तिगत जानकारी',
      'work_info': 'कार्यालय जानकारी',
      'account_settings': 'खाता सेटिंग्स',
      'change_password': 'पासवर्ड बदलें',
      'notifications': 'सूचना सेटिंग्स',
      'help_support': 'मदद और सहायता',
      'language_changed': 'भाषा बदल दी गई',
      'language_change_failed': 'भाषा बदलने में विफल',
      'select_language': 'भाषा चुनें',
      'welcome_message': 'स्वागत है, {name}!',
      'google_account_connected': 'आपका Google खाता कनेक्ट हो गया है।',
      'complaint_important': 'आपकी शिकायत महत्वपूर्ण है।',
      'home': 'घर',
      'my_complaints': 'मेरी शिकायतें',
      'pending_work': 'लंबित कार्य',
      'completed_complaints': 'पूर्ण शिकायतें',

      // Dashboard
      'officer_dashboard': 'अधिकारी डैशबोर्ड',
      'complaint_categories': 'शिकायत श्रेणियां',
      'incoming_complaints': 'आने वाली शिकायतें',
      'all_complaints': 'सभी शिकायतें',
      'resolved_complaints': 'हल की गई शिकायतें',
      'recent_complaints': 'हाल की शिकायतें',
      'view_all': 'सभी देखें',
      'main_functions': 'मुख्य कार्य',
      'complaints_management': 'शिकायत प्रबंधन',
      'notice_board': 'सूचना बोर्ड',
      'submit_complaint': 'शिकायत दर्ज करें',
      'data_updated': 'डेटा अपडेट किया गया',
      'loading_data': 'डेटा लोड हो रहा है...',

      // Complaints
      'complaints': 'शिकायतें',
      'complaint_management': 'शिकायत प्रबंधन',
      'search_complaints': 'शिकायतें खोजें...',
      'filter': 'फिल्टर',
      'all': 'सभी',
      'pending': 'लंबित',
      'in_progress': 'प्रगति में',
      'resolved': 'हल हो गई',
      'complaint_details': 'शिकायत #',
      'view_details': 'विवरण देखें',
      'update_status': 'स्थिति अपडेट करें',
      'contact_citizen': 'नागरिक से संपर्क करें',
      'no_complaints': 'कोई शिकायत नहीं मिली',
      'no_search_results': 'खोज परिणाम नहीं मिले',

      // Notice Board
      'notice_board_management': 'सूचना बोर्ड प्रबंधन',
      'all_notices': 'सभी',
      'published': 'प्रकाशित',
      'draft': 'ड्राफ्ट',
      'search_notices': 'सूचनाएं खोजें...',
      'add_notice': 'नई सूचना',
      'notice_published': 'सूचना प्रकाशित की गई',
      'notice_saved_draft': 'सूचना ड्राफ्ट में सहेजी गई',
      'notice_updated': 'सूचना अपडेट की गई',
      'notice_deleted': 'सूचना हटा दी गई',
      'delete_notice_confirm': 'क्या आप इस सूचना को हटाना चाहते हैं?',
      'delete': 'हटाएं',
      'no_notices': 'कोई सूचना नहीं मिली',

      // Officer Complaint Form
      'officer_complaint_form': 'अधिकारी शिकायत फॉर्म',
      'complaint_title': 'शिकायत का शीर्षक',
      'complaint_description': 'शिकायत का विवरण',
      'location': 'स्थान',
      'contact_number': 'संपर्क नंबर',
      'priority': 'प्राथमिकता',
      'category': 'श्रेणी',
      'submit_to_office': 'कार्यालय में दर्ज करें',
      'urgent': 'अत्यंत महत्वपूर्ण (तत्काल कार्रवाई आवश्यक)',
      'attach_files': 'फाइलें संलग्न करें',
      'gallery': 'गैलरी',
      'camera': 'कैमरा',
      'file': 'फाइल',
      'files_selected': 'फाइलें सफलतापूर्वक जोड़ी गईं',
      'photo_added': 'फोटो सफलतापूर्वक जोड़ा गया',
      'file_load_failed': 'फाइल लोड करने में विफल',
      'photo_load_failed': 'फोटो लोड करने में विफल',
      'submit': 'शिकायत दर्ज करें',
      'submitting': 'शिकायत दर्ज की जा रही है...',
      'complaint_submitted': 'शिकायत सफलतापूर्वक दर्ज की गई',
      'submission_failed': 'शिकायत दर्ज करने में विफल',
      'fill_required_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
      'attach_files_confirm': 'क्या आप फाइलें संलग्न करना चाहते हैं?',
      'add_files': 'फाइलें जोड़ें',
      'continue': 'जारी रखें',

      // Status and Priority
      'high': 'उच्च',
      'medium': 'मध्यम',
      'low': 'निम्न',
      'completed': 'पूर्ण',
      'under_review': 'समीक्षा में',
      'citizen_name': 'नागरिक का नाम',
      'submission_date': 'दर्ज करने की तारीख',
      'ward': 'वार्ड',
      'status': 'स्थिति',

      // Offices
      'district_office': 'जिला कार्यालय',
      'province_office': 'प्रांत कार्यालय',
      'central_office': 'केंद्रीय कार्यालय',
      'ministry': 'मंत्रालय',

      // Categories
      'general_administration': 'सामान्य प्रशासन',
      'infrastructure': 'बुनियादी ढांचा',
      'sanitation': 'स्वच्छता',
      'health': 'स्वास्थ्य',
      'education': 'शिक्षा',
      'security': 'सुरक्षा',
      'financial': 'वित्तीय',
      'other': 'अन्य',
    },
  };

  static String getString(String key, String languageCode) {
    return _localizedStrings[languageCode]?[key] ?? _localizedStrings['ne']?[key] ?? key;
  }

  static Map<String, String> getLanguageNames() {
    return {
      'ne': 'नेपाली',
      'en': 'English',
      'hi': 'हिन्दी',
    };
  }
}